version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "server"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tdqf6l19hchl"
s3_prefix = "server"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
